name: Build and upload APK (Android) mobile app

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '2.10.4'
      - run: flutter pub get
      - run: flutter build apk --debug
      - run: flutter build appbundle --debug

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v1
        with:
          name: debug-apk
          path: build/app/outputs/apk/debug/app-debug.apk

  screenshots:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install puppeteer-headful
        uses: mujo-code/puppeteer-headful@master
        env:
          CI: 'true'
      - name: screenshots-ci-action
        uses: flameddd/screenshots-ci-action@v1.1.1
        with:
          url: https://github.com
          devices: Pixel 2
      - uses: actions/upload-artifact@v2
        with:
          path: screenshots
          name: Download-screenshots